name: Build and Test

on:
  push:
    branches:
    - master
    - dev
    - feature/*
  pull_request:
    branches:
    - dev

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'

jobs:
  build_test_run:
    name: Build, test and run the GitHub Action
    strategy:
      matrix:
        os: [ 'windows-latest' ]
        dotnet: [ '3.1.100' ]

    runs-on: ${{ matrix.os }}

    env:
      USER_AGENT: GitHubActionsPrMerge
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v1

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Restore NuGet packages
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet restore .
        popd

    - name: Build Function app
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build . -c Release -o ./output
        popd

    - name: Test Function app
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet test test/**/*.csproj
        popd
