name: Build, Test and Deploy

on:
  push:
    branches:
    - release/*

jobs:
  build_test_run:
    name: Build, test and deploy

    runs-on: 'ubuntu-latest'

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Restore NuGet packages
      shell: bash
      run: |
        dotnet restore .

    - name: Build Function app
      shell: bash
      run: |
        dotnet build . -c Release -o ./output

    - name: Test Function app
      shell: bash
      run: |
        dotnet test . -c Release

    - name: Deploy Function app
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
        package: './output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
